name: Build and Test Bateman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential flex bison llvm-18-dev zlib1g-dev clang-18 libfl-dev libzstd-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_CXX_FLAGS="-I/usr/include" -DLLVM_DIR=/usr/lib/llvm-18/cmake

      - name: Build and test
        run: make test